name: OasisWorldGen
main: oasis.worldgen.WorldGen
version: 2.0
description: OasisWorldGen provides a mechanism to manually run world generation functions for structures.
author: Paxination
load: STARTUP
depend: [WorldEdit, WorldGuard, Multiverse-Core]

permissions:
  worldgen.*:
    description: Gives all WorldGen permissions
    children:
      worldgen.command: true
  worldgen.command:
    description: Allow user to run the worldgen command
    default: op
    children:
      worldgen.command.dungeon: true
      worldgen.command.deserttemple: true
      worldgen.command.jungletemple: true
      worldgen.command.watertemple: true
      worldgen.command.mineshaft: true
      worldgen.command.nether: true
      worldgen.command.stronghold: true
      worldgen.command.village: true
      worldgen.command.simple: true
      worldgen.command.witch: true
  worldgen.command.dungeon:
    description: Allow user to generate dungeons
    default: op
  worldgen.command.watertemple:
    description: Allow user to generate a monument/aka water temple
    default: op
  worldgen.command.deserttemple:
    description: Allow user to generate a desert temple
    default: op
  worldgen.command.jungletemple:
    description: Allow user to generate a jungle temple
    default: op
  worldgen.command.mineshaft:
    description: Allow user to generate a mineshaft complex
    default: op
  worldgen.command.nether:
    description: Allow user to generate a nether complex items
    default: op
  worldgen.command.stronghold:
    description: Allow user to generate a stronghold complex and rooms
    default: op
  worldgen.command.village:
    description: Allow user to generate a village complex
    default: op
  worldgen.command.simple:
    description: Allow user to generate a simple items (wells, mushrooms, etc)
    default: op
  worldgen.command.witch:
    description: Allow user to generate a witch's hut
    default: op
  worldgen.generate:
    description: Allow user to set the default generator for creating new worlds.
    default: op
  worldgen.addglobal:
    description: Adds a __global__ region to the region list in the world your in.
    default: op
  worldgen.deal:
    description: Deal with it!

commands:
  deal:
    description: Deal with it!
    usage: /<command>
    permission: worldgen.deal
    permission-message: You don't have permissions for <permission>
    
  addglobal:
    description: Adds a __global__ region to the region list in the world your in.
    usage: /<command>
    permission: worldgen.addglobal
    permission-message: You don't have permissions for <permission>
    
  generate:
    description: Used to generate a custom world.
    usage: /<command> [BLOCK ID#]
    permission: worldgen.generate
    permission-message: You don't have permissions for <permission>
    
  worldgen:
    description: This will generate minecraft world structures at the current player location.
    usage: /<command> [type] [radius=200].  Use [type]=help for details.
    permission: worldgen.command
    permission-message: You don't have permissions for <permission>
